apiVersion: acmeplatform.com/v1alpha1
kind: AppClaim
metadata:
  name: app-demo 
  labels:
    app-owner: melak-cmd
spec:
  id: acme-platform
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: devops-team
    image: piotrzan/nginx-demo:green
    host: nginx.127.0.0.1.nip.io
