---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-sa
  namespace: crossplane-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-gitlab
subjects:
  - kind: ServiceAccount
    name: provider-gitlab
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-sa
subjects:
  - kind: ServiceAccount
    name: provider-sa
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gitlab
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - args:
                - --debug
              name: package-runtime
              # env:
              #   - name: HTTP_PROXY
              #     value: http://172.21.32.1:3128
              #   - name: HTTPS_PROXY
              #     value: http://172.21.32.1:3128
              #   - name: NO_PROXY
              #     value: localhost,127.0.0.1,10.42.0.0/24,10.43.0.1                           
          serviceAccountName: provider-sa
  serviceAccountTemplate:
    metadata:
      name: provider-sa

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gitlab
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.7.0
  runtimeConfigRef:
    name: provider-gitlab

---
# Gitlab provider that references the secret credentials
apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  baseURL: http://gitlab.127.0.0.1.nip.io:8080/
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gitlab-creeds
      key: token

---
apiVersion: v1
data:
  token: Z2xwYXQteXhqTDM3eW02cWVMeHNDc3htN20=
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-creeds
  namespace: crossplane-system
